-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 13:25:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Examen2BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Examen2BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Examen2BD` DEFAULT CHARACTER SET utf8 ;
USE `Examen2BD` ;

-- -----------------------------------------------------
-- Table `Examen2BD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2BD`.`Usuario` (
  `NombreUsuario` VARCHAR(20) NOT NULL,
  `Contraseña` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`NombreUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2BD`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2BD`.`Productos` (
  `IdProductos` INT NOT NULL,
  `NombreProducto` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Existencia` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`IdProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2BD`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2BD`.`Pedidos` (
  `IdPedido` INT NOT NULL,
  `NombreCliente` VARCHAR(20) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `SubTotal` DECIMAL NOT NULL,
  `ISV` DECIMAL NOT NULL,
  `Total` DECIMAL NOT NULL,
  PRIMARY KEY (`IdPedido`))
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
